### ISSUE TITLE
Parent task not checked in specific case

### ISSUE THREAD

**Issue by andiandi13** [PhilKes/NotallyX#391]
### What happened?

1. Create at least two subtasks, check one of them, and move the other unchecked task away from the group : the parent task will not be checked while it should

2. Instead of moving the unchecked task, tap the delete icon, the app will crash (see attached log)

### App Version

7.1.0-BETA-Checklist

### Android Version (API Level)

29

### (Optional) Relevant log output

```shell
java.lang.NullPointerExceptionat com.philkes.notallyx.presentation.view.note.listitem.sorting.b.d(SourceFile:163)at com.philkes.notallyx.presentation.view.note.listitem.sorting.b.compare(SourceFile:5)at h0.x0.compare(SourceFile:3)at h0.z0.f(SourceFile:14)at com.philkes.notallyx.presentation.view.note.listitem.sorting.d.p(SourceFile:74)at com.philkes.notallyx.presentation.view.note.listitem.h.i(SourceFile:52)at com.philkes.notallyx.presentation.view.note.listitem.h.j(SourceFile:89)at C1.a.onClick(SourceFile:21)at android.view.View.performClick(View.java:7259)at android.view.View.performClickInternal(View.java:7236)at android.view.View.access$3600(View.java:801)at android.view.View$PerformClick.run(View.java:27892)at android.os.Handler.handleCallback(Handler.java:883)at android.os.Handler.dispatchMessage(Handler.java:100)at android.os.Looper.loop(Looper.java:214)at android.app.ActivityThread.main(ActivityThread.java:7356)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by PhilKes** [comment]
Fixed by https://github.com/PhilKes/NotallyX/pull/388/commits/7e2c337b2679bc3b66aa09b77d0cef248e6f6e4d and https://github.com/PhilKes/NotallyX/pull/388/commits/e7bfb411f60facbb08770e31733abc23b185ba56

https://github.com/user-attachments/assets/8bf57cd1-c431-4f31-9ab9-1a52b45390df

https://github.com/user-attachments/assets/33e5c862-11a3-443d-8199-372452d569c3

**Comment by PhilKes** [comment]
@andiandi13 released a new BETA `CheckedList` apk

**Comment by andiandi13** [comment]
@PhilKes I forgot one case, which the PR doesn't fix. It's when you make the unchecked subtask normal task again

https://github.com/user-attachments/assets/2466f554-536a-4b0c-9e76-d451c855524d
