### ISSUE TITLE
List item parent task becomes subtask

### ISSUE THREAD

**Issue by andiandi13** [PhilKes/NotallyX#404]
### What happened?

When sliding a parent + subtask below a parent task, it becomes subtask + subtask while excepted behavior would be to remain parent + subtask, but below the other parent task.

https://github.com/user-attachments/assets/570cb1ea-69cf-4d0a-8207-1a63b65f7e4c

### App Version

7.2.0-BETA

### Android Version (API Level)

29

### (Optional) Relevant log output

```shell

```

**Comment by PhilKes** [comment]
Fixed in https://github.com/PhilKes/NotallyX/pull/388/commits/8ee9d99213ee7faba50816cd873b1fd8b342e92a

New BETA is released

**Comment by andiandi13** [comment]
Fixed

**Comment by andiandi13** [comment]
@PhilKes Actually there's a similar issue remaining, but when you swap Parent+Subtask and other parent + subtask

https://github.com/user-attachments/assets/0698aab5-2309-481c-acab-0877fab63ece
